# Generated by Django 5.0 on 2024-01-16 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WebApplication", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
