# Generated by Django 5.0 on 2024-01-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebApplication", "0002_rename_user_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
